export class IslandScene extends Phaser.Scene {
 constructor(){super("IslandScene");}
 create(){const {width,height}=this.scale;this.worldW=Math.max(1800,width*2.5);this.worldH=Math.max(1400,height*2);this.discovered=new Set();this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBackgroundColor("#66c8e4");this.makeWater();this.makeIsland();this.makeNature();this.makeAnimals();this.makePlayer();this.makeUI(width);this.input.on("pointerdown",(p,objects)=>{if(objects?.length)return;this.target.set(p.worldX,p.worldY);this.tapRipple(p.worldX,p.worldY);});this.scale.on("resize",()=>this.scene.restart());}
 makeWater(){this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,0x63c7e6);for(let i=0;i<42;i++){const s=this.add.ellipse(Phaser.Math.Between(0,this.worldW),Phaser.Math.Between(0,this.worldH),Phaser.Math.Between(45,130),Phaser.Math.Between(4,9),0xc8f3fb,Phaser.Math.FloatBetween(.12,.3));this.tweens.add({targets:s,x:s.x+Phaser.Math.Between(35,95),alpha:{from:.1,to:.34},duration:Phaser.Math.Between(1800,3400),yoyo:true,repeat:-1,ease:"Sine.inOut"});}}
 makeIsland(){this.add.ellipse(this.worldW/2,this.worldH/2,this.worldW*.78,this.worldH*.73,0xf4dfaa);this.add.ellipse(this.worldW/2,this.worldH/2,this.worldW*.70,this.worldH*.64,0x78bb6d);this.add.rectangle(this.worldW*.50,this.worldH*.53,this.worldW*.50,108,0xd7bd91).setAngle(-9);this.add.rectangle(this.worldW*.47,this.worldH*.53,108,this.worldH*.48,0xd7bd91).setAngle(7);this.house=this.add.image(this.worldW*.66,this.worldH*.43,"house").setScale(1.28).setDepth(this.worldH*.43/10).setInteractive();this.house.on("pointerdown",()=>{this.discover("house");this.toast("おうちを みつけた！");this.tweens.add({targets:this.house,scale:1.34,duration:120,yoyo:true});});}
 makeNature(){const trees=[[.33,.34],[.42,.28],[.72,.34],[.28,.55],[.76,.60],[.37,.72],[.65,.74],[.54,.31],[.22,.42]];trees.forEach(([x,y],idx)=>{const tr=this.add.image(this.worldW*x,this.worldH*y,"tree").setScale(.82+(idx%3)*.08).setDepth(this.worldH*y/10).setInteractive();this.tweens.add({targets:tr,angle:{from:-1.3,to:1.3},duration:1500+idx*80,yoyo:true,repeat:-1,ease:"Sine.inOut"});tr.on("pointerdown",()=>{this.discover("tree");this.toast("きが ゆれた！");this.tweens.add({targets:tr,angle:{from:-8,to:8},duration:75,yoyo:true,repeat:4,onComplete:()=>tr.setAngle(0)});if(Phaser.Math.Between(0,100)<45)this.dropLeaf(tr.x,tr.y);});});[[.45,.40],[.52,.37],[.58,.54],[.43,.61],[.68,.54],[.60,.68],[.31,.64]].forEach(([x,y],idx)=>{const f=this.add.image(this.worldW*x,this.worldH*y,"flower").setScale(.65+.08*(idx%2)).setDepth(this.worldH*y/10).setInteractive();f.on("pointerdown",()=>{this.discover("flower");this.toast("おはなが ひらいた！");this.tweens.add({targets:f,scale:1.15,duration:170,yoyo:true});});});[[.54,.46],[.70,.50],[.40,.48]].forEach(([x,y])=>this.add.image(this.worldW*x,this.worldH*y,"rock").setScale(.8).setDepth(this.worldH*y/10));[[.28,.78],[.72,.77],[.80,.66]].forEach(([x,y])=>{const sh=this.add.image(this.worldW*x,this.worldH*y,"shell").setDepth(this.worldH*y/10).setScale(.8).setInteractive();sh.on("pointerdown",()=>{this.discover("shell");this.toast("かいがらを みつけた！");this.tweens.add({targets:sh,y:sh.y-35,alpha:0,duration:350,onComplete:()=>sh.destroy()});});});}
 makeAnimals(){for(let i=0;i<4;i++){const b=this.add.image(this.worldW*Phaser.Math.FloatBetween(.34,.70),this.worldH*Phaser.Math.FloatBetween(.35,.68),"butterfly").setScale(.7).setDepth(5000).setInteractive();this.tweens.add({targets:b,x:b.x+Phaser.Math.Between(-90,90),y:b.y+Phaser.Math.Between(-70,70),duration:Phaser.Math.Between(1800,3000),yoyo:true,repeat:-1,ease:"Sine.inOut"});b.on("pointerdown",()=>{this.discover("butterfly");this.toast("ちょうちょ！");this.tweens.add({targets:b,y:b.y-120,alpha:0,duration:500,onComplete:()=>b.destroy()});});}this.crab=this.add.image(this.worldW*.74,this.worldH*.79,"crab").setScale(.85).setDepth(this.worldH*.79/10).setInteractive();this.tweens.add({targets:this.crab,x:this.crab.x+90,duration:1800,yoyo:true,repeat:-1,ease:"Sine.inOut"});this.crab.on("pointerdown",()=>{this.discover("crab");this.toast("カニが にげた！");this.tweens.add({targets:this.crab,x:this.crab.x+180,alpha:0,duration:550,onComplete:()=>this.crab.destroy()});});this.time.addEvent({delay:5500,loop:true,callback:()=>this.spawnBird()});this.spawnBird();}
 makePlayer(){this.player=this.physics.add.image(this.worldW*.50,this.worldH*.61,"player").setScale(.72).setDepth(999);this.player.body.setCircle(37,10,61);this.player.setCollideWorldBounds(true);this.target=new Phaser.Math.Vector2(this.player.x,this.player.y);this.cameras.main.startFollow(this.player,true,.085,.085);this.cameras.main.setZoom(Math.max(.78,Math.min(1.05,this.scale.width/780)));}
 makeUI(width){const h=this.add.text(20,22,"⌂ ホーム",{fontFamily:"sans-serif",fontSize:21,fontStyle:"bold",color:"#31556a",backgroundColor:"#fff8dc",padding:{x:14,y:10}}).setScrollFactor(0).setDepth(99999).setInteractive();h.on("pointerdown",()=>{this.player.setVelocity(0);this.scene.start("HomeScene");});this.discoveryText=this.add.text(width-20,22,"★ きょうの発見 0/5",{fontFamily:"sans-serif",fontSize:18,fontStyle:"bold",color:"#5e5137",backgroundColor:"#fff8dc",padding:{x:12,y:10}}).setOrigin(1,0).setScrollFactor(0).setDepth(99999);this.toastText=this.add.text(width/2,92,"",{fontFamily:"sans-serif",fontSize:22,fontStyle:"bold",color:"#31556a",backgroundColor:"#ffffffe8",padding:{x:18,y:12}}).setOrigin(.5,0).setScrollFactor(0).setDepth(100000).setAlpha(0);}
 update(){if(!this.player)return;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.target.x,this.target.y);if(d>12){const a=Phaser.Math.Angle.Between(this.player.x,this.player.y,this.target.x,this.target.y),s=255;this.player.setVelocity(Math.cos(a)*s,Math.sin(a)*s);this.player.setScale(.72,.72+Math.sin(this.time.now*.02)*.02);this.player.setFlipX(Math.cos(a)<-.15);}else{this.player.setVelocity(0);this.player.setScale(.72);}this.player.setDepth(1000+this.player.y/10);}
 discover(k){this.discovered.add(k);const c=Math.min(5,this.discovered.size);this.discoveryText.setText(`★ きょうの発見 ${c}/5`);if(c===5)this.time.delayedCall(250,()=>this.celebrate());}
 toast(m){this.toastText.setText(m).setAlpha(1).setScale(.92);this.tweens.killTweensOf(this.toastText);this.tweens.add({targets:this.toastText,scale:1,duration:130,onComplete:()=>this.tweens.add({targets:this.toastText,alpha:0,delay:900,duration:350})});}
 celebrate(){this.toast("★ 5こ みつけた！ ★");for(let i=0;i<24;i++){const p=this.add.circle(this.player.x+Phaser.Math.Between(-60,60),this.player.y+Phaser.Math.Between(-50,40),Phaser.Math.Between(3,7),[0xffd85a,0xff8a65,0xffffff,0x78c9ff][i%4]).setDepth(9999);this.tweens.add({targets:p,x:p.x+Phaser.Math.Between(-100,100),y:p.y-Phaser.Math.Between(100,220),alpha:0,duration:Phaser.Math.Between(700,1200),onComplete:()=>p.destroy()});}}
 dropLeaf(x,y){const l=this.add.ellipse(x,y-45,15,8,0xf2b84b).setDepth(9998);this.tweens.add({targets:l,x:x+Phaser.Math.Between(-45,45),y:y+70,angle:220,alpha:0,duration:900,onComplete:()=>l.destroy()});}
 spawnBird(){const x=this.cameras.main.scrollX-80,y=this.cameras.main.scrollY+Phaser.Math.Between(100,260);const b=this.add.image(x,y,"bird").setDepth(9990).setAlpha(.75);this.tweens.add({targets:b,x:x+this.scale.width+260,y:y+Phaser.Math.Between(-40,40),duration:4200,ease:"Linear",onComplete:()=>b.destroy()});}
 tapRipple(x,y){const r=this.add.circle(x,y,10,0xffffff,0).setStrokeStyle(4,0xffffff,.68).setDepth(9997);this.tweens.add({targets:r,radius:42,alpha:0,duration:420,onComplete:()=>r.destroy()});}
}
